### PR TITLE
Fix #20 Directory shows all collections 

### LINKED ISSUE #20: Directory shows all collections belonging to a biobank instead of only the ones matching the filters
## How to reproduce
search query: country AT, material Plasma
## Expected result 
ALL Austrian PLASMA collections 
## Actual result 
ALL collections (any material) of Austrian Biobanks (grouped by biobank) which contains at least one Plasma-collection.

### PR DESCRIPTION
**Pull request by ConnorStroomberg**
Directory shows all collection  belonging to a biobank instea…d of only the ones matching the filters

Filter non matching collections from biobank collections

#### Checklist
- [ ] Functionality works & meets specifications
- [ ] Code reviewed
- [x] Code unit/integration/system tested
- [ ] User documentation updated
- [ ] Clean commits
- [ ] No warnings during install
- [ ] Updated flow typing

### CODE REVIEW

File: src/store/getters.js [hunk 1]
```diff
@@ -2,8 +2,16 @@ import { createRSQLQuery } from './helpers'
 import _ from 'lodash'
 
 export default {
-  loading: state => !(state.allBiobanks && state.biobankIds),
-  biobanks: (state, getters) => getters.loading ? [] : _.sortBy(state.biobankIds.map(id => state.allBiobanks[id]), 'name'),
+  loading: state => !(state.allBiobanks && state.collectionIds),
+  biobanks: (state, getters) => getters.loading ? [] : _.sortBy(
+    state.allBiobanks
+      .map(biobank => ({...biobank}))
```
Comment (fdlk) [inline src/store/getters.js]: Nice!
